# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/programowanie/verilog/lab8_median/hdmi_vga_zybo_LN/hdmi_vga_zybo_LN.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0.xci
# IP: The module: 'hdmi_vga_vp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/programowanie/verilog/lab8_median/hdmi_vga_zybo_LN/hdmi_vga_zybo_LN.srcs/sources_1/ip/delayLineBRAM/delayLineBRAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# IP: D:/programowanie/verilog/lab8_median/hdmi_vga_zybo_LN/hdmi_vga_zybo_LN.srcs/sources_1/ip/divider_32_20_0/divider_32_20_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# IP: D:/programowanie/verilog/lab8_median/hdmi_vga_zybo_LN/hdmi_vga_zybo_LN.srcs/sources_1/ip/c_accum_0/c_accum_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_accum_0 || ORIG_REF_NAME==c_accum_0} -quiet] -quiet

# IP: D:/programowanie/verilog/lab8_median/hdmi_vga_zybo_LN/hdmi_vga_zybo_LN.srcs/sources_1/ip/rgb2ycbcr_0/rgb2ycbcr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0} -quiet] -quiet

# XDC: d:/programowanie/verilog/lab8_median/hdmi_vga_zybo_LN/hdmi_vga_zybo_LN.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_vp_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/programowanie/verilog/lab8_median/hdmi_vga_zybo_LN/hdmi_vga_zybo_LN.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0.xci
# IP: The module: 'hdmi_vga_vp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/programowanie/verilog/lab8_median/hdmi_vga_zybo_LN/hdmi_vga_zybo_LN.srcs/sources_1/ip/delayLineBRAM/delayLineBRAM.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# IP: D:/programowanie/verilog/lab8_median/hdmi_vga_zybo_LN/hdmi_vga_zybo_LN.srcs/sources_1/ip/divider_32_20_0/divider_32_20_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# IP: D:/programowanie/verilog/lab8_median/hdmi_vga_zybo_LN/hdmi_vga_zybo_LN.srcs/sources_1/ip/c_accum_0/c_accum_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_accum_0 || ORIG_REF_NAME==c_accum_0} -quiet] -quiet

# IP: D:/programowanie/verilog/lab8_median/hdmi_vga_zybo_LN/hdmi_vga_zybo_LN.srcs/sources_1/ip/rgb2ycbcr_0/rgb2ycbcr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0} -quiet] -quiet

# XDC: d:/programowanie/verilog/lab8_median/hdmi_vga_zybo_LN/hdmi_vga_zybo_LN.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_vp_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
