# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/programowanie/verilog/lab8_median/hdmi_vga_zybo_LN/hdmi_vga_zybo_LN.srcs/sources_1/ip/delayLineBRAM/delayLineBRAM.xci
# IP: The module: 'delayLineBRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/programowanie/verilog/lab8_median/hdmi_vga_zybo_LN/hdmi_vga_zybo_LN.gen/sources_1/ip/delayLineBRAM/delayLineBRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'delayLineBRAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/programowanie/verilog/lab8_median/hdmi_vga_zybo_LN/hdmi_vga_zybo_LN.srcs/sources_1/ip/delayLineBRAM/delayLineBRAM.xci
# IP: The module: 'delayLineBRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/programowanie/verilog/lab8_median/hdmi_vga_zybo_LN/hdmi_vga_zybo_LN.gen/sources_1/ip/delayLineBRAM/delayLineBRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'delayLineBRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
